### ISSUE TITLE
pom中有两个依赖更新不了，请查看并确认

### ISSUE THREAD

**Issue by justein** [xuminwlt/j360-shiro#2]
j360-shiro-appclient.pom中，app-common和app-core这两个依赖更新不到。看了下可能主要是封装的http头的信息吧，如果不涉及产品核心业务的话，可否上传一下？

**Comment by xuminwlt** [comment]
修改过了，可以install，但是跑起来需要配置完整的datasource，自行配置下吧，有空这周我再修改下写个完整版

**Comment by justein** [comment]
OK，一会儿试试，看你们也用了dubbo，我们也在用，不过我们是企业应用，不是移动端的backend，有问题多多交流~

2016-08-03 

james_gosling 

发件人：徐敏 notifications@github.com
发送时间：2016-08-03 10:42
主题：Re: [xuminwlt/j360-shiro] pom中有两个依赖更新不了，请查看并确认 (#2)
收件人："xuminwlt/j360-shiro"j360-shiro@noreply.github.com
抄送："Lyn"james_gosling@163.com,"Author"author@noreply.github.com

修改过了，可以install，但是跑起来需要配置完整的datasource，自行配置下吧，有空这周我再修改下写个完整版
